// Generated by CoffeeScript 1.4.0
(function() {
  var account, action, animationDelay, count, getInstagram, getNextPhoto, photos, show, user;

  user = {
    'access_token': '11843940.f59def8.3b00c1d86a124e3b8120e1623a38ad37',
    'user': {
      'username': 'thebrigade',
      'bio': '',
      'website': 'http:\/\/www.thisisthebrigade.com',
      'profile_picture': 'http:\/\/images.instagram.com\/profiles\/profile_11843940_75sq_1340516738.jpg',
      'full_name': 'The Brigade',
      'id': '203949578'
    }
  };

  account = user;

  count = -1;

  photos = [];

  show = 15;

  animationDelay = 5000;

  action = 'fadeInUp';

  getNextPhoto = function() {
    var arrayLength, interval, photoCount;
    photoCount = 0;
    arrayLength = photos.length;
    return interval = setInterval(function() {
      var random, target;
      random = Math.round(Math.random() * show);
      target = $('.image').eq(random).find('a');
      if (arrayLength > photoCount) {
        $(target).fadeOut(function() {
          $(this).attr('href', photos[photoCount].attr('data-link'));
          $(this).find('img').attr('src', photos[photoCount].attr('src'));
          return $(target).delay(200).fadeIn();
        });
        return photoCount++;
      } else {
        return clearInterval(interval);
      }
    }, animationDelay);
  };

  getInstagram = function() {
    return $.getJSON('https://api.instagram.com/v1/users/' + account.user.id + '/media/recent?access_token=' + account.access_token + '&count=' + count + '&callback=?', function(data) {
      $.each(data.data, function(i, image) {
        var cacheImage;
        if (i < show) {
          $('<div>', {
            'class': 'image'
          }).appendTo('.instagram');
          $('<a>', {
            'class': 'animate animated ' + action,
            href: image.link
          }).appendTo('.instagram div.image:last');
          return $('<img>', {
            src: image.images.low_resolution.url,
            alt: image.images.title
          }).appendTo('.instagram div.image:last a');
        } else {
          cacheImage = $('<img>', {
            src: image.images.low_resolution.url,
            alt: 'Life at The Brigade',
            'data-link': image.link
          });
          return photos.push(cacheImage);
        }
      });
      $('.image').css('visibility', 'visible');
      return getNextPhoto();
    });
  };

  $(function() {
    return getInstagram();
  });

}).call(this);
